### PR TITLE
Make it work with rustc 1.0.0-nightly

### PR DESCRIPTION
**Pull request by soulseekah**
at rustc 1.0.0-nightly (c5961ad06 2015-01-28 21:49:38 +0000)

Renamed `std::io` to `std::old_io` since `io` is moving somewhere.
Added a couple of missing new trait requirements.

`cargo test` is still failing:

```
src/crypto/p256.rs:615:26: 615:32 error: type `[u32]` does not implement any method in scope named `fmt`
src/crypto/p256.rs:615                 self.v[].fmt(a)
                                                ^~~~~~
src/crypto/p256.rs:615:32: 615:32 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
src/crypto/p256.rs:615:32: 615:32 help: candidate #1: use `core::fmt::Debug`
src/crypto/poly1305.rs:348:24: 348:30 error: type `[u32]` does not implement any method in scope named `fmt`
src/crypto/poly1305.rs:348             (self.v[]).fmt(a)
                                                  ^~~~~~
src/crypto/poly1305.rs:348:30: 348:30 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
src/crypto/poly1305.rs:348:30: 348:30 help: candidate #1: use `core::fmt::Debug`
```

### CODE REVIEW

**Comment by klutzy** [comment]
Hmm, I actually have an update patch but not pushed to master (just pushed to [this wip branch](https://github.com/klutzy/suruga/tree/x509-parser)). I haven't frequently pushed updates because this project is not yet ready to use. I'll push it soon. Thanks anyway!
