### ISSUE TITLE
Rust nightly

### ISSUE THREAD

**Issue by soulseekah** [klutzy/suruga#5]
This will probably be an ongoing issue seeing how Rust changes all the time. Currently doesn't work with nightly rustc 1.0.0-nightly (c5961ad06 2015-01-28 21:49:38 +0000).

```
src/cipher/ecdhe.rs:2:5: 2:23 error: unresolved import `std::io::BufReader`. Could not find `io` in `std`
src/cipher/ecdhe.rs:2 use std::io::BufReader;
                          ^~~~~~~~~~~~~~~~~~
src/handshake.rs:1:5: 1:23 error: unresolved import `std::io::MemReader`. Could not find `io` in `std`
src/handshake.rs:1 use std::io::MemReader;
                       ^~~~~~~~~~~~~~~~~~
src/client.rs:1:5: 1:33 error: unresolved import `std::io::net::tcp::TcpStream`. Could not find `io` in `std`
src/client.rs:1 use std::io::net::tcp::TcpStream;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/client.rs:4:15: 4:23 error: unresolved import `std::io::IoResult`. Could not find `io` in `std`
src/client.rs:4 use std::io::{IoResult, IoError, OtherIoError};
                              ^~~~~~~~
src/client.rs:4:25: 4:32 error: unresolved import `std::io::IoError`. Could not find `io` in `std`
src/client.rs:4 use std::io::{IoResult, IoError, OtherIoError};
                                        ^~~~~~~
src/client.rs:4:34: 4:46 error: unresolved import `std::io::OtherIoError`. Could not find `io` in `std`
src/client.rs:4 use std::io::{IoResult, IoError, OtherIoError};
                                                 ^~~~~~~~~~~~
src/tls_result.rs:2:5: 2:21 error: unresolved import `std::io::IoError`. Could not find `io` in `std`
src/tls_result.rs:2 use std::io::IoError;
```

Fixed somewhat in #4 but needs more work (`cargo test` in particular).

**Comment by klutzy** [comment]
Currently fixed by #7.
